# Generated by Django 5.0.6 on 2024-06-23 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0003_alter_email_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
