# Generated by Django 5.0.6 on 2024-06-24 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0006_sent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtracking",
            old_name="Subscriber",
            new_name="subscriber",
        ),
    ]
